-- Профиль продавца
CREATE TABLE seller_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    store_name VARCHAR(150) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_seller_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_seller_profiles_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED', 'BLOCKED'))
);


-- Категории. parent_id позволяет создавать вложенные категории
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_categories_parent_id
    ON categories (parent_id);


-- Производители товаров
CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_brands_name
    ON brands (LOWER(name));


-- Карточки товаров
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    brand_id BIGINT,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_seller
        FOREIGN KEY (seller_id)
        REFERENCES seller_profiles (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
        REFERENCES brands (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_products_price
        CHECK (price > 0),

    CONSTRAINT chk_products_status
        CHECK (status IN (
            'DRAFT',
            'PUBLISHED',
            'HIDDEN',
            'BLOCKED',
            'ARCHIVED'
        ))
);

CREATE INDEX idx_products_category_status
    ON products (category_id, status);

CREATE INDEX idx_products_seller_id
    ON products (seller_id);

CREATE INDEX idx_products_price
    ON products (price);

CREATE INDEX idx_products_name
    ON products (LOWER(name));


-- Остатки товаров
CREATE TABLE inventory (
    product_id BIGINT PRIMARY KEY,
    available_quantity INTEGER NOT NULL DEFAULT 0,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_inventory_available
        CHECK (available_quantity >= 0),

    CONSTRAINT chk_inventory_reserved
        CHECK (reserved_quantity >= 0)
);


-- Изображения товаров
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_product_images_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_product_images_product_id
    ON product_images (product_id);

CREATE UNIQUE INDEX uk_product_primary_image
    ON product_images (product_id)
    WHERE is_primary = TRUE;


-- Корневые категории
INSERT INTO categories (name, slug)
VALUES
    ('Одежда', 'clothing'),
    ('Техника', 'electronics'),
    ('Мебель', 'furniture'),
    ('Обувь', 'shoes'),
    ('Товары для дома', 'home');


-- Подкатегории одежды
INSERT INTO categories (name, slug, parent_id)
SELECT values_table.name, values_table.slug, parent.id
FROM (
    VALUES
        ('Футболки', 't-shirts'),
        ('Куртки', 'jackets'),
        ('Брюки', 'trousers'),
        ('Платья', 'dresses')
) AS values_table(name, slug)
JOIN categories parent ON parent.slug = 'clothing';


-- Подкатегории техники
INSERT INTO categories (name, slug, parent_id)
SELECT values_table.name, values_table.slug, parent.id
FROM (
    VALUES
        ('Смартфоны', 'smartphones'),
        ('Ноутбуки', 'laptops'),
        ('Телевизоры', 'televisions'),
        ('Бытовая техника', 'home-appliances')
) AS values_table(name, slug)
JOIN categories parent ON parent.slug = 'electronics';


-- Подкатегории мебели
INSERT INTO categories (name, slug, parent_id)
SELECT values_table.name, values_table.slug, parent.id
FROM (
    VALUES
        ('Столы', 'tables'),
        ('Стулья', 'chairs'),
        ('Диваны', 'sofas'),
        ('Шкафы', 'wardrobes')
) AS values_table(name, slug)
JOIN categories parent ON parent.slug = 'furniture';