CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_transactions_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_payment_transactions_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_payment_transactions_idempotency_key
        UNIQUE (idempotency_key),

    CONSTRAINT chk_payment_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payment_transactions_type
        CHECK (type IN (
            'PAYMENT',
            'SELLER_PAYOUT',
            'PLATFORM_COMMISSION',
            'REFUND'
        )),

    CONSTRAINT chk_payment_transactions_status
        CHECK (status IN (
            'CREATED',
            'COMPLETED',
            'FAILED',
            'REFUNDED'
        ))
);

CREATE INDEX idx_payment_transactions_order_id
    ON payment_transactions (order_id);

CREATE INDEX idx_payment_transactions_user_id
    ON payment_transactions (user_id);
