CREATE TABLE wallet_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_wallet_accounts_user_id
        UNIQUE (user_id),

    CONSTRAINT fk_wallet_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_wallet_accounts_balance
        CHECK (balance >= 0)
);

INSERT INTO wallet_accounts (user_id, balance)
SELECT DISTINCT ur.user_id, 0
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE r.name IN ('SELLER', 'OWNER')
ON CONFLICT (user_id) DO NOTHING;
